# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: LaumosL
email: a.masullo@bristol.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  My name is Alessandro Masullo and I'm a lecturer in Digital Health, researching in Computer Vision and Multi-Sensory Fusion. 
  I'm passionate about climbing, technology, piano, cycling and photography.
github_username: ale152
minimal_mistakes_skin: default
search: false

repository: ale152/ale152.github.io

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/London # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Alessandro Masullo"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "I'm a lecturer in Digital Health, researching in Computer Vision and Multi-Sensory Fusion. 
  I'm passionate about climbing, technology, piano, cycling and photography."
  location: "Bristol, UK"
  links:
    - label: "E-mail"
      icon: "fas fa-at"
      url: "mailto:a.masullo@bristol.ac.uk"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ale152"
    - label: "University of Bristol"
      icon: "fas fa-university"
      url: "https://www.bristol.ac.uk/people/person/Alessandro-Masullo-a83495ec-647d-41eb-ae2c-3591146bdd8e/"
    - label: "Google Scholar"
      icon: "fab fa-google"
      url: "https://scholar.google.com/citations?user=J6GebsYAAAAJ"
    - label: "ORCID iD"
      icon: "fab fa-orcid"
      url: "https://orcid.org/0000-0002-6510-835X"
    - label: "Linkedin"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/alessandro-masullo/"

footer:
  links:
    - label: "E-mail"
      icon: "fas fa-at"
      url: "mailto:a.masullo@bristol.ac.uk"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
  
github: [metadata]
  
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-159914320-1"
    anonymize_ip: false # default
